### ISSUE TITLE
Improve dataset performance monitoring

### ISSUE THREAD

**Issue by imincik** [linz/geostore#1215]
So that the system is providing good user experience when users are importing data, as a devops team member, I want more context on the performance monitoring Slack message of the general performance of a dataset import.

### Acceptance Criteria
 - [x] Given a dataset import is completed, When the slack notification is made, then it includes an elapsed time from when the user made the request to when it was complete.
- [ ] Given a dataset import is completed, when the slack notification is made, then it includes a number of files validated and number of files copied.
- [ ] ~~Given a dataset is mid-import, when a hour has elapsed since the user made the request, the the team is notified via Slack that there is an unusually long data import happening.~~
- [ ] (This is probably redundant if we do #1947) ~~Given there are SQS messsages in the queue, when the SQS message has been there longer than 15 minutes, the team is notified via slack of an unusually old SQS message.~~

**Comment by Jimlinz** [comment]
Feels like there is some overlap with #1947 (last bullet point)

**Comment by billgeo** [comment]
Closing this. I think we have adequate monitoring for now.
