### ISSUE TITLE
Bug: CloudTrail buckets are not deleted after pipeline runs

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#1295]
## Bug Description

CloudTrail buckets such as ci1613238263-geostore-apicloudtrails3644380fc-7ixm6gtq952v are created during pipeline runs, but are not deleted after the run is finished. It looks like they don't end up as part of the relevant CloudFormation stack. The buckets aren't empty either, so they'll need to be emptied or forcefully removed as part of the pipeline cleanup.

This is causing us to quickly run out of the [bucket quota of 100](https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html), causing further pipelines to always fail. It also makes it impossible for CI job re-runs to work:

> Resource handler returned message: "Resource of type 'AWS::Logs::LogGroup' with identifier '{"/properties/LogGroupName":"ci1613721776-geostore-cloudtrail-api"}' already exists.

We can also [run out of trails](https://github.com/linz/geostore/runs/4755832857?check_suite_focus=true):

> ci1675258478-geostore | 12:56:48 AM | CREATE_FAILED        | AWS::CloudTrail::Trail           | api/cloudtrail (apicloudtrail31CA7546) Resource handler returned message: "Invalid request provided: User: *** already has 5 trails in ap-southeast-2. (Service: CloudTrail, Status Code: 400, Request ID: 75c002cc-a607-4367-b5f5-5431c93b8b47, Extended Request ID: null)" (RequestToken: f935d4fa-96ee-a616-ea9a-a8615b80b568, HandlerErrorCode: InvalidRequest)

## How to Reproduce

1. Run a test job

What did you expect to happen? All AWS resources created by the job should be removed at the end of the job run, whether the job was successful or not.

What actually happened? The CloudTrail bucket is left behind after the job is finished.

## Additional context

Each pipeline run creates *two* such buckets, one for the test job and one for the production upgrade job.

Manual workaround: Run `parallel --delay=1sauto --retry-failed --verbose aws s3 rb --force "s3://{}" ::: $(aws s3 ls | cut --delimiter=' ' --fields=3 | grep 'ci.*geostore')` periodically (this will break any in-progress pipelines).

#### Definition of Done

- [ ] This bug is **done**:
  - [ ] Bug resolved to **user's** satisfaction
  - [ ] Automated tests are passing
  - [ ] Code is peer reviewed and pushed to master
  - [ ] Deployed successfully to test environment
  - [ ] Checked against [CODING guidelines](https://github.com/linz/geostore/blob/master/CODING.md)
  - [ ] Relevant new tasks are added to backlog and communicated to the team
  - [ ] Important decisions recorded in the issue ticket
  - [ ] Readme/Changelog/Diagrams are updated
  - [ ] Product Owner has approved as complete
  - [ ] No regression to functional or
        [non-functional](https://github.com/linz/geostore/blob/master/.github/ISSUE_TEMPLATE/user_story.md)
        requirements

**Comment by billgeo** [comment]
@l0b0 this looks to have been looking at the PR for this. Can we close this issue?

**Comment by l0b0** [comment]
Which PR do you mean @billgeo? #1315?

**Comment by billgeo** [comment]
Yes.
