### ISSUE TITLE
Metadata Catalogue - Git Hosting

### ISSUE THREAD

**Issue by jacobus** [linz/geostore#1411]
As a user I want to be able to get to the metadata catalog website.

Note, at this point the metadata catalogue will be a simple online STAC editor for editing LINZ STAC extensions. It will simply have the options to create or upload a STAC record. Capture the fields required, and for the user to copy or download the records. This is a simple, stateless, online utility, that exposes no secrets and should not require any security.

Tasks:
- [ ] Create Git website for static STAC editor

Definition of done:
- [ ] Going to the git pages URL of the LINZ STAC editor will show the editor on any browser supported by Flutter (most current browsers)

**Comment by billgeo** [comment]
Issue moved to [linz/ds-infra-team #885](https://github.com/linz/ds-infra-team/issues/885) via [**ZenHub**](https://www.zenhub.com/)
