### ISSUE TITLE
Bug: status endpoint 'KeyError'

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#1738]
## Bug Description

Started a new version creation (dataset had one previous version) and it seemed to have finished successfully (looking at the STEP function logs), but get the error below when using the status endpoint function.

The end po

## How to Reproduce

1. Create a new version on a dataset with an exising version
1. Wait until the STEP function finishes
1. Run the status endpoint, example payload that shows the error.
```
{
  "http_method": "GET",
  "body": {
    "execution_arn": "arn:aws:states:ap-southeast-2:632223577832:execution:processingnonproddatasetversioncreation969559C1-bA6hvJSBF4WR:2022-06-12T23-43-57-941Z_3VP1G23B47GM5DYM"
  }
}
```
1. See error
```
{
  "errorMessage": "'new_version_id'",
  "errorType": "KeyError",
  "stackTrace": [
    "  File \"/var/task/geostore/import_status/entrypoint.py\", line 16, in lambda_handler\n    return handle_request(event, REQUEST_HANDLERS)\n",
    "  File \"/var/task/geostore/api_responses.py\", line 42, in handle_request\n    return request_handlers[method](event[BODY_KEY])\n",
    "  File \"/var/task/geostore/import_status/get.py\", line 33, in get_import_status\n    response_body = get_import_status_given_arn(body[EXECUTION_ARN_KEY])\n",
    "  File \"/var/task/geostore/step_function.py\", line 106, in get_import_status_given_arn\n    version_id = step_function_input[NEW_VERSION_ID_KEY]\n"
  ]
}
```

What did you expect to happen? 

What actually happened? 

## Software Context

Operating system: 

Environment: 

Relevant software versions:

-  AWS CLI: 
-  Poetry: 

#### Definition of Done

-  [ ] This bug is **done**:
   -  [ ] Bug resolved to **user's** satisfaction
   -  [ ] Automated tests are passing
   -  [ ] Code is peer reviewed and pushed to master
   -  [ ] Deployed successfully to test environment
   -  [ ] Checked against
          [CODING guidelines](https://github.com/linz/geostore/blob/master/CODING.md)
   -  [ ] Relevant new tasks are added to backlog and communicated to the team
   -  [ ] Important decisions recorded in the issue ticket
   -  [ ] Readme/Changelog/Diagrams are updated
   -  [ ] Product Owner has approved as complete
   -  [ ] No regression to functional or
          [non-functional](https://github.com/linz/geostore/blob/master/.github/ISSUE_TEMPLATE/user_story.md)
          requirements

**Comment by l0b0** [comment]
As discussed, this is because the test overlapped a deployment:

1. Your pipeline ran 11:43
1. The commit with the new version ID finished deploying at 11:52
1. You ran the status check at 11:54, resulting in the error
