### ISSUE TITLE
Bug: Some datasets not being added to the root catalog

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#1817]
## Bug Description

These datasets don't seem to appear in the root catalog.json for the Geostore (these Historic Imagery survey reference numbers which should appear in the dataset title).

- [x] 1892
- [x] 2078
- [x] 2952
- [x] 3778
- [x] 5625
- [x] 5818
- [x] 5919
- [x] 5928
- [x] 8106
- [x] 8225
- [x] 8503
- [x] 9000

## How to Reproduce

1. Do …
1. Run `…`

What did you expect to happen? 

What actually happened? 

## Software Context

Operating system: 

Environment: 

Relevant software versions:

-  AWS CLI: 
-  Poetry: 

#### Definition of Done

-  [ ] This bug is **done**:
   -  [ ] Bug resolved to **user's** satisfaction
   -  [ ] Automated tests are passing
   -  [ ] Code is peer reviewed and pushed to master
   -  [ ] Deployed successfully to test environment
   -  [ ] Checked against
          [CODING guidelines](https://github.com/linz/geostore/blob/master/CODING.md)
   -  [ ] Relevant new tasks are added to backlog and communicated to the team
   -  [ ] Important decisions recorded in the issue ticket
   -  [ ] Readme/Changelog/Diagrams are updated
   -  [ ] Product Owner has approved as complete
   -  [ ] No regression to functional or
          [non-functional](https://github.com/linz/geostore/blob/master/.github/ISSUE_TEMPLATE/user_story.md)
          requirements

**Comment by amfage** [comment]
If you look at the S3 version history of the `catalog.json` file you can see that the missing datasets were added, but they aren't contained in later versions. Maybe a timing/concurrency issue writing slightly out-of-date data to the `catalog.json` file?

**Comment by MitchellPaff** [comment]
I agree with @amfage , looks like a concurrency issue. I tried to get around this by using an SQS batch size of 1 but doesn't seem to have been enough.

I've made a further fix here https://github.com/linz/geostore/pull/1820 which sets the max concurrent executions of the populate_catalog lambda to 1.

**Comment by MitchellPaff** [comment]
i've added following to prod catalog

> 1892
> 2078
> 2952
> 3778
> 5625
> 5818
> 5919
> 5928
> 8106
> 8225
> 8503
> 9000

**Comment by billgeo** [comment]
These ones are still missing from the catalog. Coudl someone please add them in and doubel check that
 they are there. See above the method Mitch suggested for doing this.

```
5818
5919
8106
8225
```

**Comment by billgeo** [comment]
Added the four remaining links to the catalog.json.

```
Bills-MacBook-Pro:dev bill$ aws sqs send-message --message-body "historical-aerial-imagery-survey-5818/collection.json" --message-deduplication-id "duplication-01-bn" --message-group-id "group-01-bn" --queue-url "https://sqs.ap-southeast-2.amazonaws.com/715898075157/prod-geostore-processingupdatecatalogmessagequeue57A4CB2F-YUxKiJXPaAr0.fifo" --profile li-geostore-prod
{
    "MD5OfMessageBody": "165ea9c6776421ef816cbf4e92845055",
    "MessageId": "4259766f-e0bc-4cf9-b021-4a8ccbe91190",
    "SequenceNumber": "18871132205013489152"
}
Bills-MacBook-Pro:dev bill$ aws sqs send-message --message-body "historical-aerial-imagery-survey-5919/collection.json" --message-deduplication-id "duplication-02-bn" --message-group-id "group-01-bn" --queue-url "https://sqs.ap-southeast-2.amazonaws.com/715898075157/prod-geostore-processingupdatecatalogmessagequeue57A4CB2F-YUxKiJXPaAr0.fifo" --profile li-geostore-prod
{
    "MD5OfMessageBody": "d1ca89f9f2828c3f97814ed511f0c998",
    "MessageId": "e47d9e9a-970e-464a-be5c-0e6b250dbc39",
    "SequenceNumber": "18871132400418288896"
}
Bills-MacBook-Pro:dev bill$ aws sqs send-message --message-body "historical-aerial-imagery-survey-8106/collection.json" --message-deduplication-id "duplication-03-bn" --message-group-id "group-01-bn" --queue-url "https://sqs.ap-southeast-2.amazonaws.com/715898075157/prod-geostore-processingupdatecatalogmessagequeue57A4CB2F-YUxKiJXPaAr0.fifo" --profile li-geostore-prod
{
    "MD5OfMessageBody": "3f1d48b0dc831996bc506f53ea13c126",
    "MessageId": "149a7cdc-277a-4755-a134-1ce23a0d2eaf",
    "SequenceNumber": "18871132405717232896"
}
Bills-MacBook-Pro:dev bill$ aws sqs send-message --message-body "historical-aerial-imagery-survey-8225/collection.json" --message-deduplication-id "duplication-04-bn" --message-group-id "group-01-bn" --queue-url "https://sqs.ap-southeast-2.amazonaws.com/715898075157/prod-geostore-processingupdatecatalogmessagequeue57A4CB2F-YUxKiJXPaAr0.fifo" --profile li-geostore-prod
{
    "MD5OfMessageBody": "2d53bb850f58aa3655fabfb0ddfb4552",
    "MessageId": "d9c8f0a2-f20e-4ba3-90a0-fe6a37bc946c",
    "SequenceNumber": "18871132410880496128"
}

```

**Comment by billgeo** [comment]
Check that there is now the same number of links, s3 datasets, and datasets in the Geostore database.

```
Bills-MacBook-Pro:dev bill$ geostore dataset list | grep 'historical-aerial-imagery-survey-.*' | wc -l
      32
Bills-MacBook-Pro:dev bill$ cat ~/Downloads/catalog-10.json | grep '"href": "./historical-aerial-imagery-survey-.*/collection.json"' | wc -l
      32
Bills-MacBook-Pro:dev bill$ aws s3 ls s3://linz-geostore/ --profile li-geostore-prod | grep 'historical-aerial-imagery-survey-.*' | wc -l
      32
```

**Comment by billgeo** [comment]
Closing this issue. But I think we should monitor this to make sure there isn't still a bug somewhere.

**Comment by billgeo** [comment]
@l0b0 can you please review what I did here and close if everything is fine?

**Comment by l0b0** [comment]
LGTM.
