### ISSUE TITLE
Bug: Dataset version update should only be allowed for collection.json and catalog.json

### ISSUE THREAD

**Issue by Jimlinz** [linz/geostore#1916]
## Bug Description

There is nothing stopping user from submitting individual `item.json` (rather than `collection.json` or `catalog.json`) in their `datasets-version` API call. 

**For example:** 
_Note: 322802.json is used rather than collection.json_
```
aws lambda invoke --function-name=dataset-versions --invocation-type RequestResponse --cli-binary-format raw-in-base64-out --payload='{"http_method": "POST","body": {"id": "XXXXXXXXXX","metadata_url": "s3://linz-geostore-staging/historical-aerial-imagery-survey-1012/322802.json","s3_role_arn": "arn:aws:iam::12345:role/staging-users"}}' /dev/stdout
{"status_code": 201, "body": {"new_version_id": "2022-08-04T22-45-46-089Z_WRTTXD4DVV535Q5T", "execution_arn": "arn:aws:states:ap-southeast-2:12345:execution:processingdatasetversioncreation65D71092-AQmHc7jRkrwm:2022-08-04T22-45-46-089Z_WRTTXD4DVV535Q5T"}}
    "StatusCode": 200,
    "ExecutedVersion": "$LATEST"
```

Doing so allows the workflow to complete but causes a downstream process to fail in `geostore/populate_catalog/task.py`:
```
[ERROR] AssertionError
Traceback (most recent call last):
  File "/var/task/geostore/populate_catalog/task.py", line 53, in lambda_handler
    handle_message(message[BODY_KEY])
  File "/var/task/geostore/populate_catalog/task.py", line 93, in handle_message
    assert isinstance(dataset_metadata, (Catalog, Collection))
```

This AssertionError causes a message to be stuck on the sqs queue. Without a dead letter queue implementation, all subsequent messages are prevented from calling the `populate_catalog/task.py` lambda function. Datasets added to Geostore after this event are not updated in `catalog.json`.

#### Definition of Done

-  [ ] This bug is **done**:
   -  [ ] Bug resolved to **user's** satisfaction
   -  [ ] Automated tests are passing
   -  [ ] Code is peer reviewed and pushed to master
   -  [ ] Deployed successfully to test environment
   -  [ ] Checked against
          [CODING guidelines](https://github.com/linz/geostore/blob/master/CODING.md)
   -  [ ] Relevant new tasks are added to backlog and communicated to the team
   -  [ ] Important decisions recorded in the issue ticket
   -  [ ] Readme/Changelog/Diagrams are updated
   -  [ ] Product Owner has approved as complete
   -  [ ] No regression to functional or
          [non-functional](https://github.com/linz/geostore/blob/master/.github/ISSUE_TEMPLATE/user_story.md)
          requirements

**Comment by billgeo** [comment]
THanks @Jimlinz . Good catch. We probably should have a test for this. Task no.1 I guess. :smile:

**Comment by billgeo** [comment]
Testing this is blocked by https://github.com/linz/geostore/pull/2126

**Comment by billgeo** [comment]
Works! Thanks @AmrouEmad
