### ISSUE TITLE
Make SQS monitoring more human readable

### ISSUE THREAD

**Issue by mfwightman** [linz/geostore#1996]
This story has been split off from [#1947](https://github.com/linz/geostore/issues/1947) 

## User Story
So that we can respond to operational issues with the SQS queue that updates the STAC metadata, as a Geostore admin (devops team member), I want to be alerted of abnormal (and normal) behaviour in the SQS queue in a more easily human readable way.

## Acceptance Criteria
- [ ] Given an alert in the Slack channel, when user looks at it, they are able to get enough relevant info to debug and resolve the issue.
- [ ] Given there is a mixture of alerts in the Geostore Slack channel, when a user looks at the Slack channel, they are able to easily identify the different types/categories of alert (success, failure, warning etc).

## Background
In issue #1947, we got the SQS queue messages being sent to the #geostore-alerts Slack channel, in this issue we are making them easier to read and comprehend, applying formatting and editing to the messages. Similar to the existing alerts for the dataset-version step function slack message - [an example](https://linz.slack.com/archives/C024VKGKWLF/p1659912806775409)

#### Definition of Done

-  [ ] This bug is **done**:
   -  [ ] Bug resolved to **user's** satisfaction
   -  [ ] Automated tests are passing
   -  [ ] Code is peer reviewed and pushed to master
   -  [ ] Deployed successfully to test environment
   -  [ ] Checked against
          [CODING guidelines](https://github.com/linz/geostore/blob/master/CODING.md)
   -  [ ] Relevant new tasks are added to backlog and communicated to the team
   -  [ ] Important decisions recorded in the issue ticket
   -  [ ] Readme/Changelog/Diagrams are updated
   -  [ ] Product Owner has approved as complete
   -  [ ] No regression to functional or
          [non-functional](https://github.com/linz/geostore/blob/master/.github/ISSUE_TEMPLATE/user_story.md)
          requirements

**Comment by billgeo** [comment]
Done as part of #2083 . Closing.

**Comment by billgeo** [comment]
Done as part of #2083 . Closing.
