### ISSUE TITLE
Write tests for the datalake s3 bucket

### ISSUE THREAD

**Issue by SPlanzer** [linz/geostore#21]
Tests are required to validate the state of the data-lake environment and src code

### Discussion required: 
@imincik @billgeo it would be good to discuss test strategy.

I note that the latest CDK testing [docs state](https://docs.aws.amazon.com/cdk/latest/guide/testing.html):
```
currently, TypeScript is the only supported language for testing AWS CDK infrastructure, though 
we intend to eventually make this capability available in all languages supported by the AWS CDK. 
```
I am therefore expecting we
* Use the PyTest framework for unit level tests that are executed locally and via CD
* Have tests that run in CD after deployment to ensure the bucket is accessible and permissions are as expected

**Comment by l0b0** [comment]
Reopening in anticipation of A CDK assertions library for Python.
