### ISSUE TITLE
Create a whitelist of characters we can use in the Geostore

### ISSUE THREAD

**Issue by mfwightman** [linz/geostore#2105]
## User Story
As a user of the Geostore I want to know what characters I can name my data so that it can be successfully uploaded to the Geostore.

Check the discussion on [this Slack thread](https://linz.slack.com/archives/C01REDXV9EU/p1659663428388539). 
More detail on [Confluence page](https://toitutewhenua.atlassian.net/wiki/spaces/GEOD/pages/86410890/Geostore+Dataset+Naming+Conventions).

[S3 limitations of characters in S3 keys](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html). 

Speak to Daniel Silk in Topo.
Matt to set up meeting to introduce.

## Tasks
- [ ] Put whitelist of characters into [this confluence page](https://toitutewhenua.atlassian.net/l/cp/y0BfUxNM).

**Comment by Jimlinz** [comment]
For now, I think we should allow the following:

```
ascii_lowercase = 'abcdefghijklmnopqrstuvwxyz'
ascii_uppercase = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
digits = '0123456789'
macrons = 'āēīōūĀĒĪŌŪ'
special_characters = '_-.''
```

We can add to this list as appropriate.

**Comment by billgeo** [comment]
Seems like we can close this one @Jimlinz . We have a whitelist now. And can implement them in another issue later if we need to.
