### ISSUE TITLE
Bump up the Lambda memory limit to increase performance?

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#588]
### Enabler

So that Lambda jobs run with an optimal price/performance ratio, we might want to increase their maximum memory allocation

#### Acceptance Criteria

- [ ] ... 
- [ ] ...

#### Additional context

From [official docs](https://docs.aws.amazon.com/lambda/latest/dg/configuration-memory.html):

> Lambda allocates CPU power in proportion to the amount of memory configured.

We might save time (and possibly money) by increasing the maximum RAM allocation for Lambda jobs, even though they are not reaching their current limit of 128 MB.

We could try the [AWS Compute Optimizer](https://docs.aws.amazon.com/lambda/latest/dg/configuration-memory.html#configuration-memory-optimization-accept) to tweak the level automatically based on use.

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Done in https://github.com/linz/geostore/commit/a5241fee707a8b3700b24b96182153b8dbdb4d8b
