### ISSUE TITLE
Spike: OpenTopography extract data and metadata

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#739]
### Enabler

So that we can choose the best method to enable extract of data by [OpenTopography](https://opentopography.org/), we want to understand the capabilities of OpenTopography.

We already know that it can use SFTP for data, and metadata can be delivered by email with a Word document attached.

#### Acceptance Criteria

- [x] We know the options to extract data from the Geostore to OpenTopography
- [x] We know the option to extract and import metadata from the Geostore to OpenTopography
- [x] Options discussed by team and decision made on which option to use

#### Additional context

Information discovery:

- Read any docs available on the web
- Talk to [Bjorn](https://aus.delve.office.com/?p=bjohns%40linz.govt.nz&v=work) who is the relationship/contract manager with OpenTopography
- Talk to OpenTopography tech support

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Hi @l0b0 could you please look at this to refine it a bit. Do the acceptance criteria and story make sense to you? Anything add or adjust? We will want to use this for planning on Thursday, so would be good ot have it ready for then.

**Comment by l0b0** [comment]
LGTM, just fixed some wording.

**Comment by billgeo** [comment]
Email sent to Open Topography

**Comment by billgeo** [comment]
No reply, so sent a reminder email to Open Topo today,

**Comment by billgeo** [comment]
Open Topo have replied with the following info.

>> 1.	Are you okay to assume a role in our account to access data in the bucket? That’s our preferred way to provide access to externals.

> Yes should be fine - contact Matt Beckley at Open Topo to organise that. 

He did ask if we were making our data open or not.

>>2.	Can you ingest metadata from STAC json (also in the S3 bucket alongside the data)? I believe the current process is to provide a MS Word document. It’s probably not a big deal to continue with this method, but would be nice to automate it if possible.

>Yes - can consume STAC potentially as a data source for the landing page metadata. 

I think they also need ISO 19115 metadata too - TBC

> It would need the following extra data. See https://doi.org/10.5069/G9Z31WV0. e.g. If your STAC includes links to logos and graphics, survey PDF metadata, as well as all of the descriptive content about the dataset/lidar project, then it should be able to replace the Word document process. 

Confirmed that LINZ will wear the egress fees

**Comment by billgeo** [comment]
Decided to try s3 access. Info added to the user story for this and send info about exctra metadata stuff to topo processor team. Closing.
