### ISSUE TITLE
Bug: datasets endpoint returns two JSON documents

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#824]
## Bug Description

When for example creating a new dataset, two JSON documents are printed back to back to standard output. This makes parsing the response data unnecessarily complex. It should instead return a single JSON document.

## How to Reproduce

1. Run `aws lambda invoke --function-name="datasets" --payload='{"http_method": "POST", "body": {"title": "Auckland_2020", "description": "Aerial Imagery from APR 2020"}}' /dev/stdout`

What did you expect to happen? The resulting object JSON should be printed to standard output. For example:

```json
{"status_code": 201, "body": {"created_at": "2021-06-23T01:36:56.980192+0000", "pk": "DATASET#01F8V86QMM2B9ZWB4E99WBVZR1", "title": "Auckland_2020", "updated_at": "2021-06-23T01:36:56.980260+0000", "id": "01F8V86QMM2B9ZWB4E99WBVZR1"}}
```

What actually happened? The resulting object is printed first, then a HTTP API-like response object is printed separately:

```text
{"status_code": 201, "body": {"created_at": "2021-06-23T01:36:56.980192+0000", "pk": "DATASET#01F8V86QMM2B9ZWB4E99WBVZR1", "title": "Auckland_2020", "updated_at": "2021-06-23T01:36:56.980260+0000", "id": "01F8V86QMM2B9ZWB4E99WBVZR1"}}{
    "StatusCode": 200,
    "ExecutedVersion": "$LATEST"
}
```

## Further work

Once this has been fixed for this simplest Lambda response, we should also check the other Lambdas. If any of them return the same kind of HTTP API-like response we should get rid of that part of it. If we ever use API Gateway we can check whether that requires any change to our responses, but for now we should return sane JSON.

**Comment by l0b0** [comment]
Not a bug - this is just how `aws lambda invoke … /dev/stdout` works. The last parameter is the *file* to which the response object is written. The other JSON object is simply the response to the invocation itself. As @billgeo mentioned, we might need to use an API Gateway to avoid this.

**Comment by billgeo** [comment]
Upvote.
