### ISSUE TITLE
Bug: data files uploaded with 0KB

### ISSUE THREAD

**Issue by MDavidson17** [linz/geostore#892]
## Bug Description
The upload process uploaded the STAC metadata files but the data files are empty (0KB).
see `s3://nonprod-linz-geostore/test_1626227298-01FAHB6PXJ2T8K5MXKZ7C3A11K/2021-07-14T02-05-33-238Z_4Z6Q567FMG74ZRR2/`

## How to Reproduce

1. run upload process with `s3://li-historical-imagery-staging/GeostoreTestData/SURVEY_1/collection.json`

What did you expect to happen? 
data to copy 
What actually happened? 
empty data files
## Software Context

Operating system: Linux

Environment: nonprod

## Additional context
https://github.com/linz/topo-processor
Possibly related to: https://github.com/linz/geostore/issues/890, as some workaround was done to bypass this bug
all hrefs were changed to:
`"href": "collection.json"` as opposed to `"href": "./collection.json"`
or `"href": "72359.tiff"` as opposed to `"href": "./72359.tiff"`

**Comment by billgeo** [comment]
@l0b0 is this one of the bug that Topo team has confirmed is now fixed? If so, can you please close it.
