### ISSUE TITLE
Bug: `stac_version` `1.0.0-beta.2` generated by pystac

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#907]
## Bug Description

Pystac is emitting non-1.0.0 STAC version files.

## How to Reproduce

1. Create a dataset version

What did you expect to happen? The metadata files written to S3 should use STAC version `1.0.0`.

What actually happened? Metadata files have STAC version `1.0.0-beta.2`.

## Software Context

Operating system: Linux
Environment: nonprod

Relevant software versions:

- AWS CLI: N/A
- Poetry: N/A

## Additional context

We probably just need to update to https://github.com/stac-utils/pystac/releases/tag/v1.0.0

**Comment by l0b0** [comment]
Fixed in https://github.com/linz/geostore/pull/910.

**Comment by billgeo** [comment]
Tested and seems to be working well. Thanks @l0b0
